### ISSUE TITLE
GHA install JAGS fails - fix 

### ISSUE THREAD

**Issue by benjaminhlina** [poissonconsulting/jmbr#24]
Installing JAGS for Windows recently fails because SourceForge url redirects, therefore this [chunk errors](https://github.com/poissonconsulting/jmbr/blob/f585aee25924be5e07a7458a21af928c5267f380/.github/workflows/custom/before-install/action.yml#L15) as it doesn't redirect properly to download the `exe` of JAGS. 

If you replace it `curl` this will follow the redirect and have `cmd` download and install JAGS. See the following example in [mcp](https://github.com/lindeloev/mcp/blob/e5b1370879d5be8b45240d86276d9f99bcff4918/.github/workflows/check-standard.yaml#L40-L46).  

I should note I found this solution as I ran into the same issue with JAGS not installing on Windows for GHA.

**Comment by joethorley** [comment]
OK great - I've pinned the issue.

**Comment by joethorley** [comment]
thanks @krlmlr and @benjaminhlina
